### ISSUE TITLE
trouble with database section

### ISSUE THREAD

**Issue by tobyhodges** [software-tools-in-javascript/js-vs-ds#23]
I've got stuck in the database section of the capstone - I can't get the data for a given year. In despair, I cheated and looked at your code in `src/capstone/back/` and I have the same problem using that boilerplate as well. Can you see what I'm doing wrong/missing?

```js
const sqlite3 = require('sqlite3')
const fs = require('fs')

const Q_WORKSHOP_GET_SURVEY_STATS = `
select
  min(year) as year_low,
  max(year) as year_high,
  count(*) as record_count
from
  surveys
`

const Q_WORKSHOP_GET_SURVEY_DATA = `
select
  surveys.year as year,
  min(surveys.hindfoot_length) as hindfoot_min,
  avg(surveys.hindfoot_length) as hindfoot_avg,
  max(surveys.hindfoot_length) as hindfoot_max,
  min(surveys.weight) as weight_min,
  avg(surveys.weight) as weight_avg,
  max(surveys.weight) as weight_max
from
  surveys
where
  (surveys.year >= ?) and (surveys.year <= ?)
group by
  year
`

class Database {

  constructor (mode, arg) {
    switch (mode) {

    case 'direct' :
      this._inMemory(arg)
      break

    case 'memory' :
      const setup = fs.readFileSync(arg, 'utf-8')
      this._inMemory(setup)
      break

    case 'file' :
      this._inFile(arg)
      break

    default :
      fail(`Unknown mode "${mode}"`)
      break
    }
  }

  getSurveyStats (args, callback) {
    this.db.all(Q_WORKSHOP_GET_SURVEY_STATS, [], (err, rows) => {
      if (err) fail(err)
      callback(rows, undefined)
    })
  }

  getSurveyData (args, callback) {
    this.db.all(Q_WORKSHOP_GET_SURVEY_DATA, args, (err, rows) => {
      if (err) fail(err)
      callback(rows, undefined)
    })
  }

  _inMemory (script) {
    this.db = new sqlite3.Database(':memory:', sqlite3.OPEN_READWRITE, (err) => {
      if (err) fail(`In-memory database open error "${err}"`)
    })
    this.db.exec(script, (err) => {
      if (err) fail(`Unable to initialize in-memory database from "${script}"`)
    })
  }

  _inFile (path) {
    this.db = new sqlite3.Database(path, sqlite3.OPEN_READWRITE, (err) => {
      if (err) fail(`Database open error "${err}" for "${path}"`)
    })
  }
}

const fail = (msg) => {
  console.log(msg)
  process.exit(1)
}

const testdb = new Database('file', 'test-data.db')
testdb.getSurveyData([2001], (rows, err) => {console.log(rows)})
```

returns an empty array regardless of the year entered. To check, I tried `db.getSurveyStats([], (rows, err) => {console.log(rows)})` and that works just fine.

**Comment by gvwilson** [comment]
Hi @tobyhodges - if you look on line 37 of `server.js`, it has:

    db.getSurveyData([start, end], (rows, lastId) => {
      res.status(200).json(rows)
    })

i.e., the `getSurveyData` method expects a pair `[firstYear, lastYear]`. The query it triggers, called `Q_WORKSHOP_GET_SURVEY_DATA`, has two wildcards on line 25 of `database.js`:

    where                                                                                                                                                                     
        (surveys.year >= ?) and (surveys.year <= ?)

so I think that `testdb.getSurveyData([1973, 1980], (rows, err) => {...})` will do what you want. This all needs (a) documentation and (b) better names (why is the word `WORKSHOP` in that query?)

**Comment by tobyhodges** [comment]
Fair enough - this is another case of me not being able to see the wood for the trees. The`?` placeholder token in SQL is... confusing but having re-read the description of the functions in `capstone.md` I can see that this was a misunderstanding on my part. Thanks for the help, @gvwilson

**Comment by tobyhodges** [comment]
Happy to - I anyway think that, if I were writing this, I would include a test that returns something more helpful than `undefined` if the wrong number of parameters are provided. (Most of my frustration came from the not small number of different places that that `undefined` could have been coming from!) So I'll write a pair of exercises to highlight the problem and to write the test to catch it.

**Comment by tobyhodges** [comment]
Reopening as a reminder to myself to add these exercises
