### ISSUE TITLE
Have table and vis compenents work from the same data

### ISSUE THREAD

**Issue by tobyhodges** [software-tools-in-javascript/js-vs-ds#25]
Hi @gvwilson. For avoiding two separate lookups of the same data for rendering/updating the table and the visualization in the capstone project, could either of the first two suggestions here do the job? https://stackoverflow.com/questions/21285923/reactjs-two-components-communicating

I will give it a go tomorrow and (if necessary) (probably necessary) Friday.

**Comment by tobyhodges** [comment]
I'd like to change componentDidMount to an `async` function, a la:

```js
  componentDidMount = await () => {
    const url = `${this.baseUrl}/survey/stats`
    var response = await fetch(url)
    this.setState({
      summary: response.json()
    })
  }
```

**Comment by gvwilson** [comment]
I hereby do delegate, fully and irrevocably, all authority over design and implementation of all matters involved in or related to the provision of a Vega-Lite chart in the capstone example of this course to Dr. Toby Hodges. Or as Jean Luc would say, "Make it so!"

**Comment by tobyhodges** [comment]
@gvwilson does `src/capstone/front/index.html` launch without errors on your device? I'm getting `SyntaxError: import declarations may only appear at top level of a module (app.js:1)`.

**Comment by gvwilson** [comment]
What command(s) are you using to launch it?

**Comment by gvwilson** [comment]
#26 gets a clean build - when you run using Parcel, Node will automatically install Chart.js, so please don't commit changes to `package.json` that this inflicts on us.

**Comment by tobyhodges** [comment]
Ok, with a clean clone of master, `app.js` runs but I still get 

`SyntaxError: import declarations may only appear at top level of a module` 

when I open `index.html` in the browser after that.

I tried adding `type="module"` to the `script` tag in `index.html`, as suggested here: https://stackoverflow.com/questions/37624819/es2015-import-doesnt-work-even-at-top-level-in-firefox (not sure how relevant that is, though), and then got 

`SyntaxError: expected expression, got '<' (app.js:66)` instead.

@gvwilson I'm not expecting you to fix all this, don't worry! Just logging my (lack of) progress so that I can remember where to start off again in the morning.

**Comment by tobyhodges** [comment]
Ok, I can get rid of all browser console errors by changing the `script` tag to `<script src="app.js" async type="text/jsx"></script>`. Now to try to get something better than a blank page....

**Comment by tobyhodges** [comment]
Ah, scratch that. Got it.
