### ISSUE TITLE
Have learners build a small React app using the World Clock API

### ISSUE THREAD

**Issue by gvwilson** [software-tools-in-javascript/js-vs-ds#36]
<http://worldclockapi.com/api/json/cet/now> (but allow them to replace `cet` with other timezones)

**Comment by tobyhodges** [comment]
Sounds like a nice idea for an example/extended exercise. Did you have it in mind for the `interactive` chapter? I'd be happy to take this on, if you're not wedded to the idea of doing it yourself?

**Comment by gvwilson** [comment]
Yes, I was thinking of `interactive` - it'll give people practice with the cycle of "user event triggers callback which makes HTTP request which triggers callback which updates DOM which triggers React redisplay". If you're up for it, it's all yours.

**Comment by tobyhodges** [comment]
Sweet, thanks. I should be able to get something drafted during my travel back to Germany on Wednesday.

**Comment by gvwilson** [comment]
Is this worth pursuing?

**Comment by tobyhodges** [comment]
Hmmm. Could be fun but must confess I've not done anything about it yet. Let's hold onto it as an idea for an addition/enhancement on `interactive` if it looks like we need one.

**Comment by tobyhodges** [comment]
Closing this for now.
