### ISSUE TITLE
Convert to GitBook?

### ISSUE THREAD

**Issue by gvwilson** [software-tools-in-javascript/js-vs-ds#42]
@gvwilson has had mixed experiences with GitBook, but it's well documented, widely used, and just plain works - use it instead of the Youbou template?

**Comment by tobyhodges** [comment]
I have a little experience of working with GitBook - can't say that I feel particularly strongly one way or the other. For now, as you're the one burdened with the responsibility of making sure that all this renders, I defer to you.

**Comment by gvwilson** [comment]
The open version of GitBook is no longer under active development, and my experiences with bookdown have not been inspiring.
