### ISSUE TITLE
example doesn't work in Interactive

### ISSUE THREAD

**Issue by tobyhodges** [software-tools-in-javascript/js-vs-ds#55]
I can't get the multi-component example to work in `interactive.md`. When running, I get the errors:

```
ReferenceError: assignment to undeclared variable parcelRequire
ReferenceError: assignment to undeclared variable parcelRequire
ReferenceError: App is not defined
```

Do you have something in your `.babelrc` that I don't have, @gvwilson? if not, any idea what else might be the problem?

**Comment by tobyhodges** [comment]
I now have v11.2 but still seeing the same problem.

**Comment by gvwilson** [comment]
What command are you using in what directory to try to run it? (I may have broken something with a subsequent update, so I'll try running on my machine if you sent the right incantations.)

**Comment by tobyhodges** [comment]
ok, full info for reproducing error:

in a new directory, I made a copy of `package.json` and removed the `cors` line:

```json
{
  "name": "test_10-14",
  "version": "0.1.0",
  "description": "test of chapters 10-14 of JSvsDS",
  "keywords": [
    "lesson",
    "JavaScript",
    "data science"
  ],
  "main": "index.js",
  "author": "Toby Hodges",
  "license": "SEE LICENSE IN LICENSE.md",
  "homepage": "http://software-tools-in-javascript.github.io/js-vs-ds/",
  "scripts": {
    "merge": "node bin/stitch.js _config.yml docs/en docs/en/index.html docs/en/all/index.html",
    "dev": "parcel serve -p 4000",
    "lint": "eslint bin/*.js src/**/*.js",
    "standard": "standard",
    "test": "mocha",
    "words": "bin/wc.js *.md *.md *.md"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/software-tools-in-javascript/js-vs-ds.git"
  },
  "bugs": {
    "url": "https://github.com/software-tools-in-javascript/js-vs-ds/issues"
  },
  "standard": {
    "ignore": [
      "css/**"
    ]
  },
  "dependencies": {
    "babel-plugin-transform-class-properties": "^6.24.1",
    "babel-preset-react": "^6.24.1",
    "body-parser": "^1.18.3",
    "express": "^4.16.4",
    "express-winston": "^3.0.1",
    "fs-extra": "^7.0.0",
    "glob": "^7.1.3",
    "glob-promise": "^3.4.0",
    "http-server": "^0.11.1",
    "js-yaml": "^3.12.0",
    "jsdom": "^13.0.0",
    "mocha": "^5.2.0",
    "node": "^10.13.0",
    "node-fetch": "^2.2.0",
    "papaparse": "^4.6.1",
    "parcel-bundler": "^1.10.3",
    "react": "^16.6.3",
    "react-dom": "^16.6.3",
    "react-vega": "^4.0.2",
    "react-vega-lite": "^2.0.2",
    "sqlite3": "^4.0.2",
    "supertest": "^3.1.0",
    "vega": "^4.3.0",
    "vega-embed": "^3.24.2",
    "vega-lib": "^4.3.0",
    "vega-lite": "^3.0.0-rc8",
    "winston": "^3.1.0"
  },
  "devDependencies": {
    "babel-core": "^6.26.3"
  }
}
```

`.babelrc` contains:
```
{
  "presets": [
    "react"
  ],
  "plugins": [
    "transform-class-properties"
  ]
}
```

I copied the contents of `src/interactive/` into an equivalently-named subdirectory here, such that I can run

```sh
npm run dev -- src/interactive/counter-functions/index.html 
```

without errors. However,

```sh
npm run dev -- src/interactive/multi-component/index.html
```

gives a blank page and the error messages that I pasted above.

(I get the exact same behaviour when trying to run the example in `master` of my clone of `js-vs-ds` as well, but trying to build these chapters up step-by-step without `cors` to identify if & when we need it.)

**Comment by gvwilson** [comment]
I'm running in a checked-out copy of `js-vs-ds` on `master`. I deleted `node_modules` and did `npm install`, got an error report because I need Python 2.7 instead of 3.6 in order to rebuild a graphics library, ignored it for now, then ran:

```
~/js-vs-ds + master$ npm run dev -- src/interactive/multi-component/index.html 
```

and got:

```
> js-vs-ds@0.1.0 dev /Users/gvwilson/js-vs-ds
> parcel serve -p 4000 "src/interactive/multi-component/index.html"

Server running at http://localhost:4000 
✨  Built in 11.42s.
```

When I go to http://localhost:4000, I get a blank page rather than seeing "Hello, world" on the page as I should.

**Comment by tobyhodges** [comment]
yes, this is also my experience.

**Comment by gvwilson** [comment]
OK, so I've broken something. I should be able to start digging in 4-5 hours (family stuff this morning).

**Comment by gvwilson** [comment]
OK, so I've broken something. I should be able to start digging in 4-5 hours (family stuff this morning). But that "Reference Error" is now gone?

**Comment by tobyhodges** [comment]
The reference error is still there for me (I'm running Firefox v63).

No problem. As fair as I can tell, apart from in the subsequent asteroids example, you haven't used this multi-component structure anywhere else so I'm hopeful that it won't stop me testing the rest.

**Comment by gvwilson** [comment]
Where does the reference error appear and when? (I'm also in Firefox.) And do you have time to take a crack at debugging this one? I was hoping to spend this afternoon working on diagrams.

**Comment by tobyhodges** [comment]
Complete console output when I load the page:

```
Download the React DevTools for a better development experience: https://fb.me/react-devtools    react-15.0.1.js:6256:9
You are using the in-browser Babel transformer. Be sure to precompile your scripts for production - https://babeljs.io/docs/setup/    babel.js:61666:4
ReferenceError: assignment to undeclared variable parcelRequire [Learn More]    localhost:4000:14:17
ReferenceError: App is not defined [Learn More]    localhost:4000:3:1 
```

I will keep looking.

**Comment by gvwilson** [comment]
That's weird. My `.babelrc` is up to date with the `master` branch; I'll mail you my `package-lock.json` (it's too large to include in a comment).
